service:
  name: sis
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  documentation: 
    api:
      info:
        version: v1.0
        title: Simple Image Share(SIS) API
        description: Serverless Application for sharing images
    models: 
      - name: AddUser
        contentType: application/json
        schema: ${file(models/add-new-user-request.json)}
      - name: CreateImageRecordRequest
        contentType: application/json
        schema: ${file(models/create-image-record-request.json)}

    # Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

  tracing:
    lambda: true
    apiGateway: true

  environment:
    SIS_TABLE: sis-${self:provider.stage}
    USER_IMAGES_BUCKET: sis-images-${self:provider.stage}
    USER_POOL_ID: us-west-2_S9oCYx1ff
    SIGNED_URL_EXPIRATION: 300
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - dynamodb:Query
  #       - dynamodb:PutItem
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #       - dynamodb:UpdateItem
  #     Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SIS_TABLE}
  #   - Effect: Allow
  #     Action:
  #       - s3:PutObject
  #       - s3:GetObject
  #     Resource: arn:aws:s3:::${self:provider.environment.USER_IMAGES_BUCKET}/*
  
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  

functions:
  Auth:
    handler: src/lambda/auth/authorizer.handler

  GetImages :
    handler: src/lambda/http/getImages.handler
    events: 
      - http:
          method: get
          path: getImages
          cors: true

  AddUser:
    handler: src/lambda/http/addUser.handler
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:PutItem        
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SIS_TABLE}
    events:
      - http:
          authorizer: Auth
          method: post
          path: addUser
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation: 
            summary: Add a New User
            description: Add a New User
            requestModels: 
              'application/json': AddUser
              
  CreateImageRecord:
    handler: src/lambda/http/createImageRecord.handler
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:PutItem        
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SIS_TABLE}
    events:
      - http:
          authorizer: Auth
          method: post
          path: createImageRecord
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation: 
            summary: Add an Image Record to groups table
            description: Add an Image Record to groups table
            requestModels: 
              'application/json': CreateImageRecordRequest
  
  GenUrl:
    handler: src/lambda/s3/genUrl.handler
    events:
      - http:
          authorizer: Auth
          method: post
          path: genUrl
          cors: true

resources:
  Resources:
    GatewayResponseDefault4XX:
        Type: AWS::ApiGateway::GatewayResponse
        Properties:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
          ResponseType: DEFAULT_4XX
          RestApiId:
            Ref: ApiGatewayRestApi

    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties: 
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
    
    UserImageBucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: ${self:provider.environment.USER_IMAGES_BUCKET}
        CorsConfiguration: 
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods: 
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: Policy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.USER_IMAGES_BUCKET}/*'
        Bucket: !Ref UserImageBucket

    SiSTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK 
            AttributeType: S
          - AttributeName: SK 
            AttributeType: S
          # - AttributeName: userId #cognitoUserId
          #   AttributeType: S
          # - AttributeName: userName
          #   AttributeType: S
          # - AttributeName: email
          #   AttributeType: S
          # - AttributeName: imageId
          #   AttributeType: S
          # - AttributeName: imageDesc
          #   AttributeType: S
          # - AttributeName: createdAt
          #   AttributeType: S
          # - AttributeName: imageUrl
          #   AttributeType: S
          # - AttributeName: groupId
          #   AttributeType: S
          # - AttributeName: groupDesc
          #   AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        # GlobalSecondaryIndexes:
        #   - IndexName: GSI1
        #     KeySchema:
        #       - AttributeName: SK
        #         KeyType: HASH
        #       - AttributeName: PK
        #         KeyType: RANGE
            # Projection:
            #   ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.SIS_TABLE}


    